import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/(fsd)/shared/styles/globals.css";
import { TanstackProvider } from "@/app/(fsd)/app/tanstackProvider";
import { ToasterProvider } from "@/app/(fsd)/app/toasterProvider";

const inter = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  style: ['normal']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <ToasterProvider>
            <div>
              {children}
            </div>
          </ToasterProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
