import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "@/src/app/tanstackProvider";

const inter = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  style: ['normal']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <div>
            {children}
          </div>
        </TanstackProvider>
      </body>
    </html>
  );
}
